language: r
r:
  - bioc-release
  - bioc-devel
cache: packages
warnings_are_errors: false

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: seandavi@gmail.com
    on_failure: seandavi@gmail.com

